import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <li>
          <Link href="/Support">Suport</Link>
        </li>
        <li>
          <Link href="/">Home</Link>
        </li>
        {children}
      </body>
    </html>
  );
}
